```{r}
library(rio)
lkXLSX1="https://github.com/shaskaimasumac/TRABAJO-DE-ESTADISTICA/raw/master/32a%20-%20Proportion%20of%20women%20of%20reproductive%20age%20(aged%2015-49%20years)%20who%20have%20their%20need%20for%20family%20planning%20satisfied%20with%20modern%20methods_data.csv"
planningfamily=import(lkXLSX1)
```
```{r}
lkXLSX3="https://github.com/shaskaimasumac/TRABAJO-DE-ESTADISTICA/raw/master/36%20-%20Proportion%20of%20births%20attended%20by%20skilled%20health%20personnel_data.csv"
birthattended=import(lkXLSX3)
```
```{r}
str(planningfamily)
```
```{r}
planningfamily[,c(1,2,3,5,6,7,8,9,11,12,13,14,15,16,17,18,19,20,21,22,23)]=NULL
```
```{r}
planningfamily[,]=lapply(planningfamily[,], trimws,whitespace = "[\\h\\v]")
```
```{r}
str(birthattended)
```
```{r}
birthattended[,c(1,2,3,5,6,7,8,9,11,12,13,14,15,16,17,18,19,20,21,22,23)]=NULL
```

```{r}
names(planningfamily)[names(planningfamily)=="Value"]="value_for_planning_family_methods"
names(birthattended)[names(birthattended)=="Value"]="Value_for_birth_attended"
```

```{r}
womenhealthindicators=merge(birthattended,planningfamily, all.x=T, all.y=T)
```

